name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    uses: autumn-library/workflows/.github/workflows/sonar.yml@main
    with:
      github_repository: oscript-library/gitsync
    secrets:
      SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }} 
